name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare .env file
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "API_KEYS_COLLECTION=${{ secrets.API_KEYS_COLLECTION }}" >> .env
          echo "IMAGES_COLLECTION=${{ secrets.IMAGES_COLLECTION }}" >> .env
          echo "RATE_LIMIT_MINUTE=${{ secrets.RATE_LIMIT_MINUTE }}" >> .env
          echo "RATE_LIMIT_DAY=${{ secrets.RATE_LIMIT_DAY }}" >> .env
          echo "STATIC_IMAGES_DIR=${{ secrets.STATIC_IMAGES_DIR }}" >> .env
          echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env
          echo "CDN_DOMAIN=${{ secrets.CDN_DOMAIN }}" >> .env

      - name: Deploy to VPS using SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/Niji-API
            git pull
            cp /home/${{ secrets.VPS_USER }}/.env .
            docker-compose down && docker-compose up -d --build
